os: "linux"

language: python

dist: "xenial"
python: "3.7"

install:
  - pip install pipenv
  - pipenv install

script: pipenv run pelican -s publishconf.py -t theme content

deploy:
  provider: pages
  strategy: git
  repo: PybloBenavides/pablobenavides.site
  target_branch: online
  local_dir: output
  token: $GITHUB_TOKEN
  edge: true
  on:
    branch: master